/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as DashboardHomeRouteImport } from './routes/_dashboard/home'
import { Route as DashboardProfileIndexRouteImport } from './routes/_dashboard/profile/index'
import { Route as DashboardContentIndexRouteImport } from './routes/_dashboard/content/index'
import { Route as DashboardAgentsIndexRouteImport } from './routes/_dashboard/agents/index'
import { Route as DashboardAgentsFlowRouteImport } from './routes/_dashboard/agents/_flow'
import { Route as DashboardAgentsAgentIdIndexRouteImport } from './routes/_dashboard/agents/$agentId/index'
import { Route as DashboardAgentsFlowManualRouteImport } from './routes/_dashboard/agents/_flow/manual'
import { Route as DashboardAgentsAgentIdEditRouteImport } from './routes/_dashboard/agents/$agentId/edit'
import { Route as DashboardContentRequestsRequestIdIndexRouteImport } from './routes/_dashboard/content/requests/$requestId/index'
import { Route as DashboardContentRequestsRequestIdEditRouteImport } from './routes/_dashboard/content/requests/$requestId/edit'
import { Route as DashboardAgentsAgentIdContentRequestRouteImport } from './routes/_dashboard/agents/$agentId/content/request'

const DashboardAgentsRouteImport = createFileRoute('/_dashboard/agents')()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentIndexRoute = DashboardContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAgentsRoute,
} as any)
const DashboardAgentsFlowRoute = DashboardAgentsFlowRouteImport.update({
  id: '/_flow',
  getParentRoute: () => DashboardAgentsRoute,
} as any)
const DashboardAgentsAgentIdIndexRoute =
  DashboardAgentsAgentIdIndexRouteImport.update({
    id: '/$agentId/',
    path: '/$agentId/',
    getParentRoute: () => DashboardAgentsRoute,
  } as any)
const DashboardAgentsFlowManualRoute =
  DashboardAgentsFlowManualRouteImport.update({
    id: '/manual',
    path: '/manual',
    getParentRoute: () => DashboardAgentsFlowRoute,
  } as any)
const DashboardAgentsAgentIdEditRoute =
  DashboardAgentsAgentIdEditRouteImport.update({
    id: '/$agentId/edit',
    path: '/$agentId/edit',
    getParentRoute: () => DashboardAgentsRoute,
  } as any)
const DashboardContentRequestsRequestIdIndexRoute =
  DashboardContentRequestsRequestIdIndexRouteImport.update({
    id: '/content/requests/$requestId/',
    path: '/content/requests/$requestId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContentRequestsRequestIdEditRoute =
  DashboardContentRequestsRequestIdEditRouteImport.update({
    id: '/content/requests/$requestId/edit',
    path: '/content/requests/$requestId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentIdContentRequestRoute =
  DashboardAgentsAgentIdContentRequestRouteImport.update({
    id: '/$agentId/content/request',
    path: '/$agentId/content/request',
    getParentRoute: () => DashboardAgentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/home': typeof DashboardHomeRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/agents': typeof DashboardAgentsFlowRouteWithChildren
  '/agents/': typeof DashboardAgentsIndexRoute
  '/content': typeof DashboardContentIndexRoute
  '/profile': typeof DashboardProfileIndexRoute
  '/agents/$agentId/edit': typeof DashboardAgentsAgentIdEditRoute
  '/agents/manual': typeof DashboardAgentsFlowManualRoute
  '/agents/$agentId': typeof DashboardAgentsAgentIdIndexRoute
  '/agents/$agentId/content/request': typeof DashboardAgentsAgentIdContentRequestRoute
  '/content/requests/$requestId/edit': typeof DashboardContentRequestsRequestIdEditRoute
  '/content/requests/$requestId': typeof DashboardContentRequestsRequestIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/home': typeof DashboardHomeRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/agents': typeof DashboardAgentsIndexRoute
  '/content': typeof DashboardContentIndexRoute
  '/profile': typeof DashboardProfileIndexRoute
  '/agents/$agentId/edit': typeof DashboardAgentsAgentIdEditRoute
  '/agents/manual': typeof DashboardAgentsFlowManualRoute
  '/agents/$agentId': typeof DashboardAgentsAgentIdIndexRoute
  '/agents/$agentId/content/request': typeof DashboardAgentsAgentIdContentRequestRoute
  '/content/requests/$requestId/edit': typeof DashboardContentRequestsRequestIdEditRoute
  '/content/requests/$requestId': typeof DashboardContentRequestsRequestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_dashboard/home': typeof DashboardHomeRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_dashboard/agents': typeof DashboardAgentsRouteWithChildren
  '/_dashboard/agents/_flow': typeof DashboardAgentsFlowRouteWithChildren
  '/_dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/_dashboard/content/': typeof DashboardContentIndexRoute
  '/_dashboard/profile/': typeof DashboardProfileIndexRoute
  '/_dashboard/agents/$agentId/edit': typeof DashboardAgentsAgentIdEditRoute
  '/_dashboard/agents/_flow/manual': typeof DashboardAgentsFlowManualRoute
  '/_dashboard/agents/$agentId/': typeof DashboardAgentsAgentIdIndexRoute
  '/_dashboard/agents/$agentId/content/request': typeof DashboardAgentsAgentIdContentRequestRoute
  '/_dashboard/content/requests/$requestId/edit': typeof DashboardContentRequestsRequestIdEditRoute
  '/_dashboard/content/requests/$requestId/': typeof DashboardContentRequestsRequestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/home'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/agents'
    | '/agents/'
    | '/content'
    | '/profile'
    | '/agents/$agentId/edit'
    | '/agents/manual'
    | '/agents/$agentId'
    | '/agents/$agentId/content/request'
    | '/content/requests/$requestId/edit'
    | '/content/requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/home'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/agents'
    | '/content'
    | '/profile'
    | '/agents/$agentId/edit'
    | '/agents/manual'
    | '/agents/$agentId'
    | '/agents/$agentId/content/request'
    | '/content/requests/$requestId/edit'
    | '/content/requests/$requestId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/home'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_dashboard/agents'
    | '/_dashboard/agents/_flow'
    | '/_dashboard/agents/'
    | '/_dashboard/content/'
    | '/_dashboard/profile/'
    | '/_dashboard/agents/$agentId/edit'
    | '/_dashboard/agents/_flow/manual'
    | '/_dashboard/agents/$agentId/'
    | '/_dashboard/agents/$agentId/content/request'
    | '/_dashboard/content/requests/$requestId/edit'
    | '/_dashboard/content/requests/$requestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/agents': {
      id: '/_dashboard/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/home': {
      id: '/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile/': {
      id: '/_dashboard/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content/': {
      id: '/_dashboard/content/'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof DashboardContentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/': {
      id: '/_dashboard/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/_dashboard/agents/_flow': {
      id: '/_dashboard/agents/_flow'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof DashboardAgentsFlowRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/_dashboard/agents/$agentId/': {
      id: '/_dashboard/agents/$agentId/'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof DashboardAgentsAgentIdIndexRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/_dashboard/agents/_flow/manual': {
      id: '/_dashboard/agents/_flow/manual'
      path: '/manual'
      fullPath: '/agents/manual'
      preLoaderRoute: typeof DashboardAgentsFlowManualRouteImport
      parentRoute: typeof DashboardAgentsFlowRoute
    }
    '/_dashboard/agents/$agentId/edit': {
      id: '/_dashboard/agents/$agentId/edit'
      path: '/$agentId/edit'
      fullPath: '/agents/$agentId/edit'
      preLoaderRoute: typeof DashboardAgentsAgentIdEditRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/_dashboard/content/requests/$requestId/': {
      id: '/_dashboard/content/requests/$requestId/'
      path: '/content/requests/$requestId'
      fullPath: '/content/requests/$requestId'
      preLoaderRoute: typeof DashboardContentRequestsRequestIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content/requests/$requestId/edit': {
      id: '/_dashboard/content/requests/$requestId/edit'
      path: '/content/requests/$requestId/edit'
      fullPath: '/content/requests/$requestId/edit'
      preLoaderRoute: typeof DashboardContentRequestsRequestIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentId/content/request': {
      id: '/_dashboard/agents/$agentId/content/request'
      path: '/$agentId/content/request'
      fullPath: '/agents/$agentId/content/request'
      preLoaderRoute: typeof DashboardAgentsAgentIdContentRequestRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
  }
}

interface DashboardAgentsFlowRouteChildren {
  DashboardAgentsFlowManualRoute: typeof DashboardAgentsFlowManualRoute
}

const DashboardAgentsFlowRouteChildren: DashboardAgentsFlowRouteChildren = {
  DashboardAgentsFlowManualRoute: DashboardAgentsFlowManualRoute,
}

const DashboardAgentsFlowRouteWithChildren =
  DashboardAgentsFlowRoute._addFileChildren(DashboardAgentsFlowRouteChildren)

interface DashboardAgentsRouteChildren {
  DashboardAgentsFlowRoute: typeof DashboardAgentsFlowRouteWithChildren
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
  DashboardAgentsAgentIdEditRoute: typeof DashboardAgentsAgentIdEditRoute
  DashboardAgentsAgentIdIndexRoute: typeof DashboardAgentsAgentIdIndexRoute
  DashboardAgentsAgentIdContentRequestRoute: typeof DashboardAgentsAgentIdContentRequestRoute
}

const DashboardAgentsRouteChildren: DashboardAgentsRouteChildren = {
  DashboardAgentsFlowRoute: DashboardAgentsFlowRouteWithChildren,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
  DashboardAgentsAgentIdEditRoute: DashboardAgentsAgentIdEditRoute,
  DashboardAgentsAgentIdIndexRoute: DashboardAgentsAgentIdIndexRoute,
  DashboardAgentsAgentIdContentRequestRoute:
    DashboardAgentsAgentIdContentRequestRoute,
}

const DashboardAgentsRouteWithChildren = DashboardAgentsRoute._addFileChildren(
  DashboardAgentsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardAgentsRoute: typeof DashboardAgentsRouteWithChildren
  DashboardContentIndexRoute: typeof DashboardContentIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardContentRequestsRequestIdEditRoute: typeof DashboardContentRequestsRequestIdEditRoute
  DashboardContentRequestsRequestIdIndexRoute: typeof DashboardContentRequestsRequestIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardAgentsRoute: DashboardAgentsRouteWithChildren,
  DashboardContentIndexRoute: DashboardContentIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardContentRequestsRequestIdEditRoute:
    DashboardContentRequestsRequestIdEditRoute,
  DashboardContentRequestsRequestIdIndexRoute:
    DashboardContentRequestsRequestIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
