/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardOrganizationRouteImport } from './routes/_dashboard/organization'
import { Route as DashboardHomeRouteImport } from './routes/_dashboard/home'
import { Route as DashboardApikeyRouteImport } from './routes/_dashboard/apikey'
import { Route as DashboardContentIndexRouteImport } from './routes/_dashboard/content/index'
import { Route as DashboardAgentsIndexRouteImport } from './routes/_dashboard/agents/index'
import { Route as DashboardContentIdRouteImport } from './routes/_dashboard/content/$id'
import { Route as DashboardAgentsFlowRouteImport } from './routes/_dashboard/agents/_flow'
import { Route as DashboardAgentsAgentIdIndexRouteImport } from './routes/_dashboard/agents/$agentId/index'
import { Route as CallbackOrganizationInvitationInviteIdRouteImport } from './routes/callback/organization/invitation/$inviteId'
import { Route as DashboardAgentsFlowManualRouteImport } from './routes/_dashboard/agents/_flow/manual'
import { Route as DashboardAgentsAgentIdEditRouteImport } from './routes/_dashboard/agents/$agentId/edit'
import { Route as DashboardAgentsAgentIdContentRequestRouteImport } from './routes/_dashboard/agents/$agentId/content/request'

const DashboardAgentsRouteImport = createFileRoute('/_dashboard/agents')()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationRoute = DashboardOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApikeyRoute = DashboardApikeyRouteImport.update({
  id: '/apikey',
  path: '/apikey',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentIndexRoute = DashboardContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAgentsRoute,
} as any)
const DashboardContentIdRoute = DashboardContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsFlowRoute = DashboardAgentsFlowRouteImport.update({
  id: '/_flow',
  getParentRoute: () => DashboardAgentsRoute,
} as any)
const DashboardAgentsAgentIdIndexRoute =
  DashboardAgentsAgentIdIndexRouteImport.update({
    id: '/$agentId/',
    path: '/$agentId/',
    getParentRoute: () => DashboardAgentsRoute,
  } as any)
const CallbackOrganizationInvitationInviteIdRoute =
  CallbackOrganizationInvitationInviteIdRouteImport.update({
    id: '/callback/organization/invitation/$inviteId',
    path: '/callback/organization/invitation/$inviteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAgentsFlowManualRoute =
  DashboardAgentsFlowManualRouteImport.update({
    id: '/manual',
    path: '/manual',
    getParentRoute: () => DashboardAgentsFlowRoute,
  } as any)
const DashboardAgentsAgentIdEditRoute =
  DashboardAgentsAgentIdEditRouteImport.update({
    id: '/$agentId/edit',
    path: '/$agentId/edit',
    getParentRoute: () => DashboardAgentsRoute,
  } as any)
const DashboardAgentsAgentIdContentRequestRoute =
  DashboardAgentsAgentIdContentRequestRouteImport.update({
    id: '/$agentId/content/request',
    path: '/$agentId/content/request',
    getParentRoute: () => DashboardAgentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/apikey': typeof DashboardApikeyRoute
  '/home': typeof DashboardHomeRoute
  '/organization': typeof DashboardOrganizationRoute
  '/profile': typeof DashboardProfileRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/agents': typeof DashboardAgentsFlowRouteWithChildren
  '/content/$id': typeof DashboardContentIdRoute
  '/agents/': typeof DashboardAgentsIndexRoute
  '/content': typeof DashboardContentIndexRoute
  '/agents/$agentId/edit': typeof DashboardAgentsAgentIdEditRoute
  '/agents/manual': typeof DashboardAgentsFlowManualRoute
  '/callback/organization/invitation/$inviteId': typeof CallbackOrganizationInvitationInviteIdRoute
  '/agents/$agentId': typeof DashboardAgentsAgentIdIndexRoute
  '/agents/$agentId/content/request': typeof DashboardAgentsAgentIdContentRequestRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/apikey': typeof DashboardApikeyRoute
  '/home': typeof DashboardHomeRoute
  '/organization': typeof DashboardOrganizationRoute
  '/profile': typeof DashboardProfileRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/agents': typeof DashboardAgentsIndexRoute
  '/content/$id': typeof DashboardContentIdRoute
  '/content': typeof DashboardContentIndexRoute
  '/agents/$agentId/edit': typeof DashboardAgentsAgentIdEditRoute
  '/agents/manual': typeof DashboardAgentsFlowManualRoute
  '/callback/organization/invitation/$inviteId': typeof CallbackOrganizationInvitationInviteIdRoute
  '/agents/$agentId': typeof DashboardAgentsAgentIdIndexRoute
  '/agents/$agentId/content/request': typeof DashboardAgentsAgentIdContentRequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_dashboard/apikey': typeof DashboardApikeyRoute
  '/_dashboard/home': typeof DashboardHomeRoute
  '/_dashboard/organization': typeof DashboardOrganizationRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_dashboard/agents': typeof DashboardAgentsRouteWithChildren
  '/_dashboard/agents/_flow': typeof DashboardAgentsFlowRouteWithChildren
  '/_dashboard/content/$id': typeof DashboardContentIdRoute
  '/_dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/_dashboard/content/': typeof DashboardContentIndexRoute
  '/_dashboard/agents/$agentId/edit': typeof DashboardAgentsAgentIdEditRoute
  '/_dashboard/agents/_flow/manual': typeof DashboardAgentsFlowManualRoute
  '/callback/organization/invitation/$inviteId': typeof CallbackOrganizationInvitationInviteIdRoute
  '/_dashboard/agents/$agentId/': typeof DashboardAgentsAgentIdIndexRoute
  '/_dashboard/agents/$agentId/content/request': typeof DashboardAgentsAgentIdContentRequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/apikey'
    | '/home'
    | '/organization'
    | '/profile'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/agents'
    | '/content/$id'
    | '/agents/'
    | '/content'
    | '/agents/$agentId/edit'
    | '/agents/manual'
    | '/callback/organization/invitation/$inviteId'
    | '/agents/$agentId'
    | '/agents/$agentId/content/request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/apikey'
    | '/home'
    | '/organization'
    | '/profile'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/agents'
    | '/content/$id'
    | '/content'
    | '/agents/$agentId/edit'
    | '/agents/manual'
    | '/callback/organization/invitation/$inviteId'
    | '/agents/$agentId'
    | '/agents/$agentId/content/request'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/apikey'
    | '/_dashboard/home'
    | '/_dashboard/organization'
    | '/_dashboard/profile'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_dashboard/agents'
    | '/_dashboard/agents/_flow'
    | '/_dashboard/content/$id'
    | '/_dashboard/agents/'
    | '/_dashboard/content/'
    | '/_dashboard/agents/$agentId/edit'
    | '/_dashboard/agents/_flow/manual'
    | '/callback/organization/invitation/$inviteId'
    | '/_dashboard/agents/$agentId/'
    | '/_dashboard/agents/$agentId/content/request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CallbackOrganizationInvitationInviteIdRoute: typeof CallbackOrganizationInvitationInviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/agents': {
      id: '/_dashboard/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organization': {
      id: '/_dashboard/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof DashboardOrganizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/home': {
      id: '/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apikey': {
      id: '/_dashboard/apikey'
      path: '/apikey'
      fullPath: '/apikey'
      preLoaderRoute: typeof DashboardApikeyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content/': {
      id: '/_dashboard/content/'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof DashboardContentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/': {
      id: '/_dashboard/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/_dashboard/content/$id': {
      id: '/_dashboard/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof DashboardContentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/_flow': {
      id: '/_dashboard/agents/_flow'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof DashboardAgentsFlowRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/_dashboard/agents/$agentId/': {
      id: '/_dashboard/agents/$agentId/'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof DashboardAgentsAgentIdIndexRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/callback/organization/invitation/$inviteId': {
      id: '/callback/organization/invitation/$inviteId'
      path: '/callback/organization/invitation/$inviteId'
      fullPath: '/callback/organization/invitation/$inviteId'
      preLoaderRoute: typeof CallbackOrganizationInvitationInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/agents/_flow/manual': {
      id: '/_dashboard/agents/_flow/manual'
      path: '/manual'
      fullPath: '/agents/manual'
      preLoaderRoute: typeof DashboardAgentsFlowManualRouteImport
      parentRoute: typeof DashboardAgentsFlowRoute
    }
    '/_dashboard/agents/$agentId/edit': {
      id: '/_dashboard/agents/$agentId/edit'
      path: '/$agentId/edit'
      fullPath: '/agents/$agentId/edit'
      preLoaderRoute: typeof DashboardAgentsAgentIdEditRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/_dashboard/agents/$agentId/content/request': {
      id: '/_dashboard/agents/$agentId/content/request'
      path: '/$agentId/content/request'
      fullPath: '/agents/$agentId/content/request'
      preLoaderRoute: typeof DashboardAgentsAgentIdContentRequestRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
  }
}

interface DashboardAgentsFlowRouteChildren {
  DashboardAgentsFlowManualRoute: typeof DashboardAgentsFlowManualRoute
}

const DashboardAgentsFlowRouteChildren: DashboardAgentsFlowRouteChildren = {
  DashboardAgentsFlowManualRoute: DashboardAgentsFlowManualRoute,
}

const DashboardAgentsFlowRouteWithChildren =
  DashboardAgentsFlowRoute._addFileChildren(DashboardAgentsFlowRouteChildren)

interface DashboardAgentsRouteChildren {
  DashboardAgentsFlowRoute: typeof DashboardAgentsFlowRouteWithChildren
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
  DashboardAgentsAgentIdEditRoute: typeof DashboardAgentsAgentIdEditRoute
  DashboardAgentsAgentIdIndexRoute: typeof DashboardAgentsAgentIdIndexRoute
  DashboardAgentsAgentIdContentRequestRoute: typeof DashboardAgentsAgentIdContentRequestRoute
}

const DashboardAgentsRouteChildren: DashboardAgentsRouteChildren = {
  DashboardAgentsFlowRoute: DashboardAgentsFlowRouteWithChildren,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
  DashboardAgentsAgentIdEditRoute: DashboardAgentsAgentIdEditRoute,
  DashboardAgentsAgentIdIndexRoute: DashboardAgentsAgentIdIndexRoute,
  DashboardAgentsAgentIdContentRequestRoute:
    DashboardAgentsAgentIdContentRequestRoute,
}

const DashboardAgentsRouteWithChildren = DashboardAgentsRoute._addFileChildren(
  DashboardAgentsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardApikeyRoute: typeof DashboardApikeyRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardOrganizationRoute: typeof DashboardOrganizationRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardAgentsRoute: typeof DashboardAgentsRouteWithChildren
  DashboardContentIdRoute: typeof DashboardContentIdRoute
  DashboardContentIndexRoute: typeof DashboardContentIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApikeyRoute: DashboardApikeyRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardOrganizationRoute: DashboardOrganizationRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardAgentsRoute: DashboardAgentsRouteWithChildren,
  DashboardContentIdRoute: DashboardContentIdRoute,
  DashboardContentIndexRoute: DashboardContentIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CallbackOrganizationInvitationInviteIdRoute:
    CallbackOrganizationInvitationInviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
